module.exports = {
    id: { type: String, required: true },
    game: { type: String, required: true },
    runners: { type: Array, required: true },
    description: { type: String },
    eventId: { type: Number, required: true },
    startTime: { type: Date },
    endTime: { type: Date },
    order: { type: Number, required: true },
    estimate: { type: String, required: true },
    finalTime: { type: String },
    category: { type: String, required: true },
    releaseYear: { type: Number },
    console: { type: String },
    finalSetupTime: { type: String },
    notes: { type: String },
    multiplayer: { type: Boolean, required: true },
    incentives: { type: Boolean, required: true },
}